name: Build and deploy ARC Backend to Azure Web App - Arc-pawan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'   # Node 18 LTS is stable (22.x avoid karo)

      - name: npm install, build, and test (backend only)
        working-directory: backend
        run: |
          npm ci
          npm run build --if-present
          npm test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6380C80720DA4964B42FA3E8C2D12705 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6ABFE9F96057415DBEDC2DCA93F71B71 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B2CDFAB167DF44ABB4FC86648930F0BF }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Arc-pawan'   # <- Azure Web App name from portal
          slot-name: 'Production'
          package: .
